version: '3'
services:
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_DB: swift_test
      POSTGRES_USER: swift
      POSTGRES_PASSWORD: swift
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: swift_test
      MYSQL_USER: swift
      MYSQL_PASSWORD: swift
      MYSQL_ROOT_PASSWORD: swift
  swift:
    build: .
    command: bundle exec rake test
    volumes:
      - .:/usr/src/app
    depends_on:
      - postgres
      - mysql
